### ISSUE TITLE
Add support for globs in dependencies/no-unresolved

### ISSUE THREAD

**Issue by pdehaan** [zertosh/eslint-plugin-dependencies#5]
I have the following .eslintrc.yml file, but it feels like a glob may be a bit easier.

```yaml
plugins:
  - dependencies
  - react

rules:
  "dependencies/case-sensitive": warn
  "dependencies/no-cycles": warn
  "dependencies/no-unresolved": [warn, {ignore: [chrome, sdk, sdk/request, sdk/timers, sdk/tabs, sdk/querystring, sdk/system, sdk/view/core, sdk/panel, sdk/simple-storage, sdk/self, sdk/page-mod, sdk/context-menu, sdk/system/events, sdk/frame/hidden-frame]}]
  "dependencies/require-json-ext": warn
```

For `dependencies/no-unresolved`, it'd be nice if I could do something like `{ignore: [chrome, sdk, "sdk/*"]}` instead of specifying each dependency separately.
